# Generated by Django 3.2.9 on 2022-01-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('mac_address', models.CharField(max_length=10, unique=True)),
                ('connection_type', models.CharField(max_length=10)),
            ],
        ),
    ]
