# Generated by Django 3.2.9 on 2022-01-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteRobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
